name: CI

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
        node: [ '14', '16' ]
    name: Build and Test(Node ${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm run lint
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Show coverage in comments
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: npm run jest --coverage
