name: CI/CD
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
        node: [ '14', '16' ]
    runs-on: ${{matrix.os}}
    name: Build and Test(Node ${{ matrix.node }} on ${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
#      - name: Show coverage in comments
#        if: ${{ !env.ACT }}
#        uses: hayuna/jest-reporter-action@v0.1.2
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          test-command: npx jest --coverage
