name: release
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]
        node: [ '14', '16' ]
    runs-on: ${{matrix.os}}
    name: Build and Test(Node ${{ matrix.node }} on ${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
